server:
  port: 9003
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
    register-with-eureka: false